export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const TRAININGLOG_START = "TRAININGLOG_START";
export const TRAININGLOG_SUCCESS = "TRAININGLOG_SUCCESS";
export const TRAININGLOG_FAIL = "TRAININGLOG_FAIL";
