export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const TRAININGLOG_START = "TRAININGLOG_START";
export const TRAININGLOG_SUCCESS = "TRAININGLOG_SUCCESS";
export const TRAININGLOG_FAIL = "TRAININGLOG_FAIL";

export const FETCH_TRAININGS_START = "FETCH_TRAININGS_START";
export const FETCH_TRAININGS_SUCCESS = "FETCH_TRAININGS_SUCCESS";
export const FETCH_TRAININGS_FAIL = "FETCH_TRAININGS_FAIL";

export const CREATE_CHART_START = "CREATE_CHART_START";
export const CREATE_CHART_SUCCESS = "CREATE_CHART_SUCCESS";
export const CREATE_CHART_FAIL = "CREATE_CHART_FAIL";

export const FETCH_STATISTICS_START = "FETCH_STATISTICS_START";
export const FETCH_STATISTICS_SUCCESS = "FETCH_STATISTICS_SUCCESS";
export const FETCH_STATISTICS_FAIL = "FETCH_STATISTICS_FAIL";
