version: "3"

services:
  # Frontend
  frontend:
    image: karosowa/thesis:latest
    stdin_open: true
    build:
      context: .
    ports:
      - "80:3000"

  #Backend
  backend:
    image: karosowka-server
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - my-network

  # DB for backend
  mongo:
    image: mongo:4.2.7-bionic
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: example
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodb:/data/db
    networks:
      - my-network

volumes:
  mongodb:

networks:
  my-network:
    driver: bridge
