version: "3"

services:
  # Backend
  frontend:
    image: karosowa/thesis:latest
    stdin_open: true
    build:
      context: .
    ports:
      - "3000:3000"

  # DB for backend
  postgres:
    image: postgres:11
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
