version: "3"

services:
  # Backend
  frontend:
    image: karosowa/thesis:latest
    stdin_open: true
    build:
      context: .
    ports:
      - "3000:3000"

  # DB for backend
  postgres:
    image: postgres:11
    hostname: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    restart: unless-stopped
    networks:
      - my-network

volumes:
  pgdata:

networks:
  my-network:
    driver: bridge
